# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - windows
julia:
  - 1.4
  - nightly
notifications:
  email: false

script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
